### ISSUE TITLE
Webpack2 support?

### ISSUE THREAD

**Issue by ijse** [mikevercoelen/icons-loader#7]
I found it not work well with webpack2 for now.

**Comment by OlivierCo** [comment]
well, let me tell you exactly what it returns, it doesn't work at all with WP2...

**Comment by roshantarudkar** [comment]
@OlivierCo is this loader supports with webpack2 now? or any other alternate loader to do this job?

**Comment by ijse** [comment]
I use `external-svg-sprite-loader` instead, and it works fine.
